---
name: treka
description: Your transport friend. Always
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: null
  cloud_firestore: null
  firebase_auth:
  firebase_core: null
  firebase_messaging:
  flutter_google_places: null
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  geocoder: null
  geoflutterfire: ^2.2.2
  geolocator: null
  google_maps_flutter: null
  google_maps_webservice: null
  http: null
  location: null
  geocoding: null
  percent_indicator: ^3.0.1
  provider: null
  get: 4.1.4
  shared_preferences: ^2.0.5
  uuid: null
  url_launcher: ^6.0.3
  get_it: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/
